"""Public re-exports for the SSH MCP server library."""

from lib.auth import AuthResult, AuthorizationManager, RulesSnapshot
from lib.config import build_default_config, ConfigManager
from lib.config_migration import migrate_config
from lib.command_security import (
    check_dangerous_patterns,
    segment_command,
    split_command_segments as segment_command_chunks,
    strip_redirects,
)
from lib.constants import (
    ACTIVE_LOG_FILENAME,
    ACTIVE_LOG_FILENAME,
    API_KEY_HASH_PREFIX,
    APP_NAME,
    APP_VERSION,
    BYTES_PER_KB,
    BYTES_PER_MB,
    SIZE_UNIT_MULTIPLIERS,
    CONFIG_BACKUP_SUFFIX,
    DANGEROUS_UNICODE_PATH_CHARS,
    LATEST_CONFIG_VERSION,
    DEFAULT_REQUEST_ID,
    DEFAULT_TRUSTED_PROXIES,
    FALLBACK_CLIENT_IP,
    MIGRATED_FILE_MODE,
    REDIRECT_FD_DUP_RE,
    REDIRECT_FILE_OP_RE,
    PROTECTED_REDIRECT_TARGET_RE,
    DEFAULT_COMMAND_TIMEOUT_SECONDS,
    DEFAULT_CONFIG_DIR,
    DEFAULT_CONFIG_FILENAME,
    DEFAULT_LOG_BACKUP_COUNT,
    DEFAULT_REDOGS_TIMEOUT_SECONDS,
    REDOGS_DANGEROUS_PATTERNS,
    DEFAULT_LOG_DIR,
    DEFAULT_LOG_MAX_SIZE_MB,
    DEFAULT_MAX_CONCURRENT_SSH_CONNECTIONS,
    DEFAULT_MAX_FILE_SIZE_BYTES,
    DEFAULT_MAX_OUTPUT_LENGTH,
    DEFAULT_RATE_LIMIT_REQUESTS,
    DEFAULT_RATE_LIMIT_WINDOW_SECONDS,
    DEFAULT_SECRETS_FILENAME,
    DEFAULT_SFTP_SANDBOX_ROOT,
    DEFAULT_SHUTDOWN_TIMEOUT_SECONDS,
    DEFAULT_SSH_KEY_FILENAME,
    MCP_SSH_CONFIG_PATH,
    MCP_SSH_LOG_DIR,
    MCP_SSH_SECRET_PREFIX,
    MCP_SSH_SETTING_PREFIX,
    MCP_SSH_SSH_KEY,
    RESTRICTED_FILE_MODE,
    SECRETS_FILE_MODE,
    SETTING_KEY_TYPES,
    DEFAULT_SSH_PORT,
    DEFAULT_SSH_TIMEOUT_SECONDS,
    DEFAULT_WATCHER_DEBOUNCE_SECONDS,
    DEFAULT_WATCHER_INTERVAL_SECONDS,
    PBKDF2_ALGO,
    PBKDF2_HASH_FUNC,
    PBKDF2_ITERATIONS,
    PBKDF2_SALT_BYTES,
    PEM_HEADER_OPENSSH,
    PEM_HEADER_PKCS8,
    PEM_HEADER_RSA,
    HTTP_SERVICE_UNAVAILABLE,
    RATE_LIMIT_CLEANUP_INTERVAL_SECONDS,
    SUDO_NO_PASSWORD_FLAG,
    SUDO_PASSWORD_PROMPT_FLAGS,
    MAX_API_KEY_LENGTH,
    MAX_BLOCK_PATTERNS,
    MAX_REGEX_PATTERN_LENGTH,
    MAX_TARGET_NAME_LENGTH,
    MAX_TARGETS,
    TARGET_NAME_PATTERN,
)
from lib.crypto import hash_api_key, verify_api_key
from lib.exceptions import (
    AuthorizationError,
    ConfigError,
    ConfigMigrationError,
    ConfigValidationError,
    FileTransferError,
    MCPSSHError,
    PathValidationError,
    RateLimitError,
    SecretsError,
    ServiceUnavailableError,
    ShutdownError,
    SSHConnectionError,
)
from lib.file_transfer import FileTransferService
from lib.rate_limiter import RateLimiter, RateLimitMiddleware
from lib.redos_protection import (
    check_redos_risk,
    compile_safe_pattern,
    safe_regex_search,
)
from lib.secrets import SecretsManager
from lib.size_utils import parse_size_bytes
from lib.request_context import (
    get_api_key,
    get_client_ip,
    get_current_request,
    get_request_id,
    RequestContextMiddleware,
)
from lib.ssh_client import SSHClientManager
from lib.sudo import SudoHandler
from lib.sanitize import (
    sanitize_command,
    sanitize_log_string,
    sanitize_target_name,
    validate_log_path,
)
from lib.types import (
    AllowedCommand,
    AllowedCommandsResult,
    CommandError,
    CommandResult,
    FileDownloadResult,
    FileUploadResult,
    HealthCheckResult,
    ServerInfo,
    ServerListResult,
    SSHTarget,
)

__all__ = [
    # Input sanitization — path validation
    "validate_log_path",
    # Command security
    "check_dangerous_patterns",
    "segment_command",
    "segment_command_chunks",
    "strip_redirects",
    # Rate limiting
    "RateLimiter",
    "RateLimitMiddleware",
    # ReDoS protection
    "check_redos_risk",
    "compile_safe_pattern",
    "safe_regex_search",
    "DEFAULT_REDOGS_TIMEOUT_SECONDS",
    "REDOGS_DANGEROUS_PATTERNS",
    # Services
    "SudoHandler",
    "SSHClientManager",
    "FileTransferService",
    "FileTransferError",
    "PathValidationError",
    "MCPSSHError",
    "ConfigError",
    "ConfigMigrationError",
    "ConfigValidationError",
    "SSHConnectionError",
    "AuthorizationError",
    "RateLimitError",
    "SecretsError",
    "ServiceUnavailableError",
    "ShutdownError",
    "build_default_config",
    "ConfigManager",
    "migrate_config",
    "AuthResult",
    "AuthorizationManager",
    "RulesSnapshot",
    "SecretsManager",
    "parse_size_bytes",
    # Request context
    "get_api_key",
    "get_client_ip",
    "get_current_request",
    "get_request_id",
    "RequestContextMiddleware",
    # Input sanitization
    "sanitize_command",
    "sanitize_log_string",
    "sanitize_target_name",
    # Crypto
    "hash_api_key",
    "verify_api_key",
    # Constants
    "ACTIVE_LOG_FILENAME",
    "ACTIVE_LOG_FILENAME",
    "APP_NAME",
    "APP_VERSION",
    "DEFAULT_CONFIG_DIR",
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_LOG_DIR",
    "DEFAULT_SECRETS_FILENAME",
    "DEFAULT_SSH_KEY_FILENAME",
    "MCP_SSH_CONFIG_PATH",
    "MCP_SSH_LOG_DIR",
    "MCP_SSH_SECRET_PREFIX",
    "MCP_SSH_SETTING_PREFIX",
    "MCP_SSH_SSH_KEY",
    "RESTRICTED_FILE_MODE",
    "SECRETS_FILE_MODE",
    "SETTING_KEY_TYPES",
    "API_KEY_HASH_PREFIX",
    "PBKDF2_ALGO",
    "PBKDF2_HASH_FUNC",
    "PBKDF2_ITERATIONS",
    "PBKDF2_SALT_BYTES",
    "MAX_TARGET_NAME_LENGTH",
    "MAX_API_KEY_LENGTH",
    "MAX_BLOCK_PATTERNS",
    "MAX_REGEX_PATTERN_LENGTH",
    "MAX_TARGETS",
    "TARGET_NAME_PATTERN",
    "PEM_HEADER_OPENSSH",
    "PEM_HEADER_RSA",
    "PEM_HEADER_PKCS8",
    "DEFAULT_WATCHER_DEBOUNCE_SECONDS",
    "DEFAULT_WATCHER_INTERVAL_SECONDS",
    "DEFAULT_SSH_PORT",
    "DEFAULT_SSH_TIMEOUT_SECONDS",
    "DEFAULT_COMMAND_TIMEOUT_SECONDS",
    "DEFAULT_MAX_CONCURRENT_SSH_CONNECTIONS",
    "DEFAULT_MAX_OUTPUT_LENGTH",
    "BYTES_PER_KB",
    "BYTES_PER_MB",
    "SIZE_UNIT_MULTIPLIERS",
    "CONFIG_BACKUP_SUFFIX",
    "LATEST_CONFIG_VERSION",
    "MIGRATED_FILE_MODE",
    "REDIRECT_FD_DUP_RE",
    "REDIRECT_FILE_OP_RE",
    "PROTECTED_REDIRECT_TARGET_RE",
    "DEFAULT_MAX_FILE_SIZE_BYTES",
    "DEFAULT_MAX_SFTP_PATH_LENGTH",
    "DEFAULT_SFTP_SANDBOX_ROOT",
    "DANGEROUS_UNICODE_PATH_CHARS",
    "DEFAULT_SHUTDOWN_TIMEOUT_SECONDS",
    "DEFAULT_LOG_MAX_SIZE_MB",
    "DEFAULT_LOG_BACKUP_COUNT",
    "DEFAULT_RATE_LIMIT_REQUESTS",
    "DEFAULT_RATE_LIMIT_WINDOW_SECONDS",
    "RATE_LIMIT_CLEANUP_INTERVAL_SECONDS",
    "HTTP_SERVICE_UNAVAILABLE",
    "SUDO_PASSWORD_PROMPT_FLAGS",
    "SUDO_NO_PASSWORD_FLAG",
    "FALLBACK_CLIENT_IP",
    "DEFAULT_REQUEST_ID",
    "DEFAULT_TRUSTED_PROXIES",
    # Types
    "ServerInfo",
    "ServerListResult",
    "AllowedCommand",
    "AllowedCommandsResult",
    "CommandResult",
    "CommandError",
    "FileDownloadResult",
    "FileUploadResult",
    "HealthCheckResult",
    "SSHTarget",
]
