"""SSH client management: connection creation and key loading."""

import hashlib
import json
import os
import random
import socket
import time
from contextlib import contextmanager
from typing import Any, Dict, Generator

import paramiko
from paramiko import SSHClient, Ed25519Key, RSAKey, AutoAddPolicy

from lib.circuit_breaker import CircuitBreaker
from lib.connection_pool import SSHConnectionPool
from lib.constants import (
    DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    DEFAULT_CIRCUIT_BREAKER_TIMEOUT_SECONDS,
    DEFAULT_RETRY_BACKOFF_BASE_SECONDS,
    DEFAULT_RETRY_MAX_ATTEMPTS,
    DEFAULT_SSH_PORT,
    DEFAULT_SSH_TIMEOUT_SECONDS,
    LOG_FORMAT_VERSION,
    PEM_HEADER_OPENSSH,
    PEM_HEADER_PKCS8,
    PEM_HEADER_RSA,
)
from lib.loggers import BaseLogger
from lib.metrics import (
    SSH_CONNECTION_DURATION_SECONDS,
    SSH_CONNECTIONS_TOTAL,
)
from lib.exceptions import (
    SSHAuthenticationError,
    SSHConnectionError,
    SSHTimeoutError,
)


class SSHClientManager:
    """Manages SSH client creation and key loading.

    Handles PEM header inspection to determine key format and creates
    appropriately configured Paramiko SSH clients for connecting to targets.
    Transient connection failures are retried with exponential backoff, and a
    per-target circuit breaker fails fast for targets that keep failing.

    Thread safety
    -------------
    Holds no mutable state of its own beyond the attached pool/circuit
    breaker (set once at wiring time via ``set_connection_pool``).  Connection
    checkout/return is delegated to :class:`~lib.connection_pool.SSHConnectionPool`,
    which owns all locking; this manager is effectively stateless per call and
    safe for concurrent use once wiring is complete.
    """

    # PEM header dispatch: maps header line to key loader function
    _KEY_LOADERS: Dict[str, Any] = {
        PEM_HEADER_OPENSSH: lambda f: Ed25519Key.from_private_key(f),
        PEM_HEADER_RSA: lambda f: RSAKey.from_private_key(f),
        PEM_HEADER_PKCS8: lambda f: Ed25519Key.from_private_key(f),
    }

    def __init__(
        self,
        default_timeout: int = DEFAULT_SSH_TIMEOUT_SECONDS,
        retry_max_attempts: int = DEFAULT_RETRY_MAX_ATTEMPTS,
        retry_backoff_base_seconds: float = DEFAULT_RETRY_BACKOFF_BASE_SECONDS,
        circuit_breaker: CircuitBreaker | None = None,
        connection_pool: SSHConnectionPool | None = None,
        logger: BaseLogger | None = None,
    ):
        """Initialize the SSH client manager.

        Args:
            default_timeout: Default connection timeout in seconds.
            retry_max_attempts: Maximum number of connection attempts
                (including the first) for transient failures.
            retry_backoff_base_seconds: Base delay (seconds) for exponential
                backoff between retries.
            circuit_breaker: Optional per-target circuit breaker.  A new one
                is created when omitted.
            connection_pool: Optional :class:`SSHConnectionPool`.  When
                attached, :meth:`connect` checks out reusable connections
                from the pool instead of always opening a new one, and
                returns them on exit instead of closing.  ``None`` (the
                default) preserves the close-on-exit behaviour.
            logger: Optional :class:`BaseLogger` for structured
                ``ssh.connect`` / ``ssh.disconnect`` lifecycle events.
                When ``None``, no lifecycle events are emitted.
        """
        self._default_timeout = default_timeout
        self._retry_max_attempts = max(1, retry_max_attempts)
        self._retry_backoff_base_seconds = retry_backoff_base_seconds
        self._circuit_breaker = circuit_breaker or CircuitBreaker()
        self._connection_pool: SSHConnectionPool | None = connection_pool
        self._logger: BaseLogger | None = logger

    def set_connection_pool(self, connection_pool: SSHConnectionPool | None) -> None:
        """Attach (or detach) the connection pool used by :meth:`connect`.

        With a pool attached, ``connect()`` registers the target with the
        pool, checks out a reusable connection, and returns it on exit
        instead of closing it.  Passing ``None`` restores the original
        close-on-exit behaviour.  The pool must already be started (or
        started afterwards) by the caller.
        """
        self._connection_pool = connection_pool

    def _load_ssh_key(self, key_path: str):
        """Load an SSH private key, detecting the format from the PEM header.

        Checks the first line of the key file to determine whether it's:
        - OPENSSH format (Ed25519, generated by `ssh-keygen -t ed25519`)
        - RSA PKCS#1 format (legacy RSA keys)
        - PKCS#8 format (generic container, assumed Ed25519)

        Args:
            key_path: Path to the SSH private key file.

        Returns:
            A paramiko key object (Ed25519Key or RSAKey).

        Raises:
            ValueError: If the key format cannot be determined.
            FileNotFoundError: If the key file does not exist.
        """
        with open(key_path) as f:
            header = f.readline().strip().strip("-")

        loader = self._KEY_LOADERS.get(header)
        if not loader:
            raise ValueError(f"Unsupported key format in {key_path}: {header}")

        with open(key_path) as f:
            return loader(f)

    @staticmethod
    def _target_name(target: Dict[str, Any]) -> str:
        """Return a stable, credential-aware identifier for *target*.

        ``host:port`` alone is not a safe key: two configured targets can
        share the same host and port while authenticating differently (e.g.
        a working password target and a broken-password target pointing at
        the same host).  Keying the pool by ``host:port`` alone makes those
        targets collide, so the pool could serve the wrong credentials.

        A short non-reversible digest of the ``auth`` payload is therefore
        appended.  The digest is computed with SHA-256, so the raw password
        or key path is never exposed here -- this key is used in Prometheus
        labels (``target=``) and structured lifecycle logs.
        """
        base = (
            f"{target.get('host', 'unknown')}:{target.get('port', DEFAULT_SSH_PORT)}"
        )
        auth = target.get("auth")
        if not auth:
            return base
        return f"{base}#{SSHClientManager._auth_digest(auth)}"

    @staticmethod
    def _auth_digest(auth: Dict[str, Any]) -> str:
        """Return a short SHA-256 digest of an ``auth`` payload.

        Serialises with sorted keys so the digest is stable regardless of
        dict ordering, and truncates to 16 hex chars to keep the derived
        pool key compact.  The digest is one-way: the credential can never
        be recovered from the returned value, which is safe to place in
        metrics labels and logs.
        """
        blob = json.dumps(auth, sort_keys=True, default=str)
        return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16]

    @staticmethod
    def _is_transient(exc: BaseException) -> bool:
        """Return True when *exc* is a transient, retryable SSH failure.

        Transient failures are network-level timeouts and connection errors
        (refused, reset, aborted, broken pipe) plus generic paramiko SSH
        errors.  Authentication failures and permanent configuration errors
        (e.g. a missing key file) are never retried.
        """
        if isinstance(exc, SSHTimeoutError):
            return True
        if isinstance(exc, (socket.timeout, TimeoutError)):
            return True
        if isinstance(exc, ConnectionError):
            return True
        if isinstance(exc, paramiko.AuthenticationException):
            return False
        if isinstance(exc, paramiko.SSHException):
            return True
        if isinstance(exc, OSError):
            # FileNotFoundError / PermissionError are OSError subclasses but
            # signal permanent local problems, not transient network issues.
            return isinstance(exc, (ConnectionResetError, ConnectionAbortedError,
                                    ConnectionRefusedError, BrokenPipeError))
        return False

    def _backoff_delay(self, attempt: int) -> float:
        """Exponential backoff with jitter for the given retry *attempt*.

        ``delay = base * 2^attempt + random(0, base)`` where *attempt* is
        zero-based (the first retry after the initial failure).
        """
        base = self._retry_backoff_base_seconds
        return base * (2 ** attempt) + random.uniform(0.0, base)

    def _sleep_before_retry(self, attempt: int) -> None:
        """Sleep for the backoff delay before retry *attempt*."""
        time.sleep(self._backoff_delay(attempt))

    def _connect_once(self, target: Dict[str, Any]) -> SSHClient:
        """Create and connect a client in a single attempt (no retries)."""
        client = SSHClient()
        client.set_missing_host_key_policy(AutoAddPolicy())

        host = target["host"]
        port = target.get("port", DEFAULT_SSH_PORT)
        username = target["username"]
        auth = target["auth"]

        connect_kwargs = {
            "hostname": host,
            "port": port,
            "username": username,
            "timeout": self._default_timeout,
        }

        if auth["type"] == "key":
            key_path = os.path.expanduser(auth["key_filename"])
            connect_kwargs["pkey"] = self._load_ssh_key(key_path)
        elif auth["type"] == "password":
            connect_kwargs["password"] = auth["password"]
        else:
            raise ValueError(f"Unsupported auth type: {auth['type']}")

        client.connect(**connect_kwargs)
        return client

    def get_client(self, target: Dict[str, Any]) -> SSHClient:
        """Create and connect an SSH client for the given target.

        Handles key-based and password-based authentication. Expands the
        key path if it contains a tilde (~).  Transient connection failures
        (timeouts, refused/reset connections, generic paramiko errors) are
        retried with exponential backoff up to ``retry_max_attempts`` times.
        Permanent failures (auth errors, unsupported auth types, missing key
        files) fail immediately.

        Args:
            target: SSH target dictionary with host, port, username, and auth config.
                   Auth config: {"type": "key", "key_filename": "..."} or
                               {"type": "password", "password": "..."}

        Returns:
            A connected paramiko.SSHClient instance.

        Raises:
            paramiko.SSHException: On connection or authentication failure.
            ValueError: If auth type is unsupported.
        """
        for attempt in range(self._retry_max_attempts):
            try:
                return self._connect_once(target)
            except (SSHTimeoutError, socket.timeout, TimeoutError, ConnectionError,
                    OSError, paramiko.SSHException) as exc:
                if not self._is_transient(exc):
                    raise
                if attempt + 1 < self._retry_max_attempts:
                    self._sleep_before_retry(attempt)
                else:
                    raise
        # Unreachable: _retry_max_attempts is always >= 1 and every loop
        # iteration either returns a client or raises.
        raise RuntimeError("unreachable: SSH retry loop exhausted without result")

    @contextmanager
    def connect(self, target: Dict[str, Any]) -> Generator[SSHClient, None, None]:
        """Context manager that creates and auto-closes an SSH connection.

        Yields a connected :class:`paramiko.SSHClient` and guarantees
        ``client.close()`` is called on exit, even if an error occurs.

        The per-target circuit breaker is consulted before connecting; when
        the circuit is open, a :class:`SSHConnectionError` is raised
        immediately (fail fast).  Successful operations reset the circuit;
        connection failures count towards opening it.

        Args:
            target: SSH target dictionary (same format as
                    :meth:`get_client`).

        Yields:
            A connected :class:`paramiko.SSHClient` instance.

        Raises:
            SSHAuthenticationError: When paramiko reports an
                authentication failure (bad credentials or rejected key).
            SSHTimeoutError: When the connection or an operation times out.
            SSHConnectionError: Wraps any other connection failure from
                paramiko or the OS, or when the circuit breaker is open.
        """
        target_name = self._target_name(target)
        if not self._circuit_breaker(target_name):
            raise SSHConnectionError(
                f"SSH connection to {target.get('host', 'unknown')} "
                f"blocked by circuit breaker (open)"
            )

        client = None
        connect_started = time.monotonic()
        try:
            if self._connection_pool is not None:
                self._connection_pool.register_target(target_name, target)
                client = self._connection_pool.get_connection(target_name)
            else:
                client = self.get_client(target)
            self._log_lifecycle("ssh.connect", target, target_name, success=True)
            SSH_CONNECTIONS_TOTAL.labels(target=target_name).inc()
            SSH_CONNECTION_DURATION_SECONDS.labels(
                target=target_name
            ).observe(time.monotonic() - connect_started)
            yield client
        except paramiko.AuthenticationException as exc:
            self._log_lifecycle("ssh.connect", target, target_name, success=False)
            raise SSHAuthenticationError(
                f"SSH authentication to {target.get('host', 'unknown')} "
                f"failed: {exc}"
            ) from exc
        except socket.timeout as exc:
            self._circuit_breaker.record_failure(target_name)
            self._log_lifecycle("ssh.connect", target, target_name, success=False)
            raise SSHTimeoutError(
                f"SSH connection to {target.get('host', 'unknown')} "
                f"timed out: {exc}"
            ) from exc
        except (paramiko.SSHException, OSError) as exc:
            self._circuit_breaker.record_failure(target_name)
            self._log_lifecycle("ssh.connect", target, target_name, success=False)
            raise SSHConnectionError(
                f"SSH connection to {target.get('host', 'unknown')} "
                f"failed: {exc}"
            ) from exc
        else:
            self._circuit_breaker.record_success(target_name)
        finally:
            if client is not None:
                self._return_to_pool(target, target_name, client)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _return_to_pool(
        self,
        target: Dict[str, Any],
        target_name: str,
        client: SSHClient,
    ) -> None:
        """Return *client* to the attached pool, or close it when no pool.

        With a pool attached, the connection is handed back to the pool
        for reuse (or closed by the pool when it is unhealthy or the
        target's idle limit is reached).  Without a pool, the client is
        closed directly, preserving the historical close-on-exit
        behaviour.  Always logs the ``ssh.disconnect`` lifecycle event.
        """
        if self._connection_pool is not None:
            self._connection_pool.return_connection(target_name, client)
        else:
            try:
                client.close()
            except Exception:
                pass
        self._log_lifecycle("ssh.disconnect", target, target_name, success=True)

    def _log_lifecycle(
        self,
        event: str,
        target: Dict[str, Any],
        target_name: str,
        success: bool,
    ) -> None:
        """Emit a structured SSH lifecycle event if a logger is configured."""
        if self._logger is None:
            return
        import datetime

        from lib.request_context import get_request_id

        self._logger.log(
            {
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "event": event,
                "level": "INFO" if success else "ERROR",
                "host": target.get("host", "unknown"),
                "port": target.get("port", DEFAULT_SSH_PORT),
                "target": target_name,
                "success": success,
                "request_id": get_request_id(),
                "log_level": "INFO" if success else "ERROR",
                "log_format_version": LOG_FORMAT_VERSION,
            }
        )
